# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

# Disable debug package generation
%global debug_package %{nil}

Name:           steamos-manager
Version:        {{{ git_dir_version }}}
Release:        1%{?dist}
Summary:        SteamOS Manager daemon for running various tasks as root

License:        MIT

URL:            https://github.com/bazzite-org/steamos-manager/
VCS:            {{{ git_dir_vcs }}}
Source:        	{{{ git_dir_pack }}}
Source1:        steamos-manager-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  cargo
BuildRequires:  rust-packaging
BuildRequires:  systemd-rpm-macros
BuildRequires:  clang-devel
BuildRequires:  cmake
BuildRequires:  rust
BuildRequires:  rust-std-static
BuildRequires:  desktop-file-utils
BuildRequires:  glib2-devel
BuildRequires:  speech-dispatcher-devel
BuildRequires:  pkgconfig(expat)
BuildRequires:  pkgconfig(gbm)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(libseat)
BuildRequires:  pkgconfig(libudev)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(libzstd)

%description

%prep
%autosetup -n {{{ git_dir_name }}} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install

# See Makefile
# Create the necessary directories
install -d -m0755 %{buildroot}%{_datadir}/dbus-1/interfaces/
install -d -m0755 %{buildroot}%{_datadir}/dbus-1/services/
install -d -m0755 %{buildroot}%{_datadir}/dbus-1/system-services/
install -d -m0755 %{buildroot}%{_sysconfdir}/dbus-1/system.d/
install -d -m0755 %{buildroot}%{_unitdir}/
install -d -m0755 %{buildroot}%{_userunitdir}/gamescope-session-plus.service.wants/

install -D -m755 target/release/steamos-manager %{buildroot}%{_bindir}/steamos-manager
install -D -m755 target/release/steamosctl %{buildroot}%{_bindir}/steamosctl
install -D -m644 -t "%{buildroot}%{_datadir}/steamos-manager/devices" "data/devices/"*
install -D -m644 LICENSE %{buildroot}%{_datadir}/licenses/%{name}/LICENSE

install -m644 "data/platform.toml" "%{buildroot}%{_datadir}/steamos-manager/"
install -D -m644 -t "%{buildroot}%{_datadir}/dbus-1/interfaces/" "data/interfaces/"*

install -m644 data/system/com.steampowered.SteamOSManager1.service %{buildroot}%{_datadir}/dbus-1/system-services/
install -m644 data/system/com.steampowered.SteamOSManager1.conf %{buildroot}%{_sysconfdir}/dbus-1/system.d/
install -m644 data/system/steamos-manager.service %{buildroot}%{_unitdir}/
#install -m644 "data/system/reset-oneshot-boot.conf" "$(DESTDIR)/usr/lib/systemd/system/sddm.service.d/"

install -m644 data/user/com.steampowered.SteamOSManager1.service %{buildroot}%{_datadir}/dbus-1/services/
install -m644 data/user/steamos-manager.service %{buildroot}%{_userunitdir}/
install -m644 data/user/steamos-manager-session-cleanup.service %{buildroot}%{_userunitdir}/
install -m644 data/user/orca.service %{buildroot}%{_userunitdir}/

# Create a symlink for the systemd service
ln -s ../steamos-manager.service %{buildroot}%{_userunitdir}/gamescope-session-plus.service.wants/steamos-manager.service

# Do post-installation
%post
%systemd_post steamos-manager.service

# Do before uninstallation
%preun
%systemd_preun steamos-manager.service

# Do after uninstallation
%postun
%systemd_postun_with_restart steamos-manager.service

%files
%license %{_datadir}/licenses/%{name}/LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md

%{_bindir}/steamosctl
%{_bindir}/steamos-manager
%{_datadir}/steamos-manager/devices/*
# license above

%{_datadir}/steamos-manager/platform.toml
%{_datadir}/dbus-1/interfaces/*

%{_datadir}/dbus-1/system-services/com.steampowered.SteamOSManager1.service
%{_sysconfdir}/dbus-1/system.d/com.steampowered.SteamOSManager1.conf
%{_unitdir}/steamos-manager.service
# %{_unitdir}/steamos-manager-reset-oneshot-boot.conf

%{_datadir}/dbus-1/services/com.steampowered.SteamOSManager1.service
%{_userunitdir}/steamos-manager.service
%{_userunitdir}/steamos-manager-session-cleanup.service
%{_userunitdir}/orca.service

# Symlink for gamescope-session
%{_userunitdir}/gamescope-session-plus.service.wants/steamos-manager.service

%changelog
%autochangelog
